services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todoapp
      PORT: 8090
      FRONTEND_URL: "http://localhost:3000"
      GIN_MODE: release # for production `release`, for testing `test`, for debugging `debug`
      APP_NAME: MinimalDo
      SIGNOZ_GPRC_ENDPOINT: "localhost:4317"
      ENABLE_CONSOLE_LOG: "true"
      LOG_LEVEL: "debug" # debug, info, warn, error
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    environment:
      REACT_APP_API_URL: "http://localhost:8090/api"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
