name: CI Frontend (MinimalDo)

env:
  FRONTEND_WORKING_DIR: "frontend"
  FRONTNED_IMAGE_NAME: "minimaldo-frontend"
  BACKEND_API_URL: "http://localhost:8080/api"

on:
  workflow_dispatch:
  
  push:
    branches: [ main ]
    paths:
      - frontend/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # This allows pushing to GHCR

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set commit ID
        id: commit
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ${{ env.FRONTEND_WORKING_DIR }}
        run: |
          echo "Building image for commit: ${{ steps.commit.outputs.short_sha }}"
          docker build \
            --build-arg REACT_APP_API_URL=${{ env.BACKEND_API_URL }} \
            -t ghcr.io/${{ github.repository_owner }}/${{ env.FRONTNED_IMAGE_NAME }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ env.FRONTNED_IMAGE_NAME }}:${{ steps.commit.outputs.short_sha }}  .

      - name: Push Docker image
        working-directory: ${{ env.BACKEND_WORKING_DIR }}
        run: |
          echo "Pushing images for commit: ${{ steps.commit.outputs.short_sha }}"
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.FRONTNED_IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.FRONTNED_IMAGE_NAME }}:${{ steps.commit.outputs.short_sha }}
